Repository 9oormthon-univ/2025_SEASONTHON_TEAM_16_BE, pull requests merged in 2025-09, with the labels that each got.

#32 docs/#31: Swagger 설명 업데이트
  src/main/java/com/seasonthon/YEIN/ai/api/HandwritingAnalysisController.java
  src/main/java/com/seasonthon/YEIN/gallery/api/GalleryController.java
Labels: docs

#33 feat/#30: 필사 커뮤니티 API 구현
  src/main/java/com/seasonthon/YEIN/global/code/status/ErrorStatus.java
  src/main/java/com/seasonthon/YEIN/post/api/PostController.java
  src/main/java/com/seasonthon/YEIN/post/api/ScrapController.java
  src/main/java/com/seasonthon/YEIN/post/api/dto/request/PostRequest.java
  src/main/java/com/seasonthon/YEIN/post/api/dto/response/PostListResponse.java
  src/main/java/com/seasonthon/YEIN/post/api/dto/response/PostResponse.java
  src/main/java/com/seasonthon/YEIN/post/application/PostService.java
  src/main/java/com/seasonthon/YEIN/post/application/ScrapService.java
  src/main/java/com/seasonthon/YEIN/post/domain/Post.java
  src/main/java/com/seasonthon/YEIN/post/domain/Scrap.java
  src/main/java/com/seasonthon/YEIN/post/domain/repository/PostRepository.java
  src/main/java/com/seasonthon/YEIN/post/domain/repository/ScrapRepository.java
  src/main/java/com/seasonthon/YEIN/user/domain/User.java
Labels: feat

#44 feat/#43: 코드래빗 설정 추가
  .coderabbit.yml
Labels: feat

#54 feat/#53: 필사 갤러리 삭제 API 구현
  src/main/java/com/seasonthon/YEIN/gallery/api/GalleryController.java
  src/main/java/com/seasonthon/YEIN/gallery/application/GalleryService.java
Labels: feat

#56 feat/#55: 커뮤니티 게시글 제목 필드 추가
  src/main/java/com/seasonthon/YEIN/post/api/dto/request/PostRequest.java
  src/main/java/com/seasonthon/YEIN/post/api/dto/response/PostListResponse.java
  src/main/java/com/seasonthon/YEIN/post/api/dto/response/PostResponse.java
  src/main/java/com/seasonthon/YEIN/post/application/PostService.java
  src/main/java/com/seasonthon/YEIN/post/domain/Post.java
Labels: feat

#64 feat/#62: 사용자가 스크랩한 게시글 조회
  src/main/java/com/seasonthon/YEIN/post/api/ScrapController.java
  src/main/java/com/seasonthon/YEIN/post/application/ScrapService.java
  src/main/java/com/seasonthon/YEIN/post/domain/repository/ScrapRepository.java
Labels: feat

#65 feat/#63: 필사 갤러리 사용자 기분 기쁨 추가
  src/main/java/com/seasonthon/YEIN/gallery/api/dto/request/GalleryUploadRequest.java
  src/main/java/com/seasonthon/YEIN/gallery/api/dto/response/GalleryDetailResponse.java
  src/main/java/com/seasonthon/YEIN/gallery/api/dto/response/GalleryResponse.java
  src/main/java/com/seasonthon/YEIN/gallery/domain/MoodTag.java
Labels: feat

#67 feat/#66: 필사 갤러리 당일 항목 조회
  src/main/java/com/seasonthon/YEIN/gallery/api/GalleryController.java
  src/main/java/com/seasonthon/YEIN/gallery/application/GalleryService.java
Labels: feat

#75 feat/#72 펫 API 구현
  src/main/java/com/seasonthon/YEIN/ai/application/HandwritingAnalysisService.java
  src/main/java/com/seasonthon/YEIN/global/code/status/ErrorStatus.java
  src/main/java/com/seasonthon/YEIN/pet/api/PetController.java
  src/main/java/com/seasonthon/YEIN/pet/api/dto/request/PetUpdateRequest.java
  src/main/java/com/seasonthon/YEIN/pet/api/dto/response/PetStatusResponse.java
  src/main/java/com/seasonthon/YEIN/pet/application/PetService.java
  src/main/java/com/seasonthon/YEIN/pet/domain/PetType.java
  src/main/java/com/seasonthon/YEIN/pet/domain/UserPet.java
  src/main/java/com/seasonthon/YEIN/pet/domain/repository/UserPetRepository.java
  src/main/java/com/seasonthon/YEIN/user/domain/User.java
Labels: feat

#78 feat/#76: 펫 변경 및 이름 변경 API 구현
  src/main/java/com/seasonthon/YEIN/pet/api/PetController.java
  src/main/java/com/seasonthon/YEIN/pet/api/dto/request/PetNameUpdateRequest.java
  src/main/java/com/seasonthon/YEIN/pet/api/dto/request/PetUpdateRequest.java
  src/main/java/com/seasonthon/YEIN/pet/application/PetService.java
  src/main/java/com/seasonthon/YEIN/pet/domain/PetType.java
Labels: feat

#80 feat/#79: 커뮤니티 댓글 API 구현
  src/main/java/com/seasonthon/YEIN/comment/api/CommentController.java
  src/main/java/com/seasonthon/YEIN/comment/api/dto/request/CommentRequest.java
  src/main/java/com/seasonthon/YEIN/comment/api/dto/response/CommentResponse.java
  src/main/java/com/seasonthon/YEIN/comment/api/dto/response/MyCommentResponse.java
  src/main/java/com/seasonthon/YEIN/comment/application/CommentService.java
  src/main/java/com/seasonthon/YEIN/comment/domain/Comment.java
  src/main/java/com/seasonthon/YEIN/comment/domain/repository/CommentRepository.java
  src/main/java/com/seasonthon/YEIN/global/code/status/ErrorStatus.java
  src/main/java/com/seasonthon/YEIN/post/domain/Post.java
Labels: feat

#82 feat/#81: 사용자 프로필 수정 API 구현
  src/main/java/com/seasonthon/YEIN/user/api/UserController.java
  src/main/java/com/seasonthon/YEIN/user/api/dto/request/UpdateProfileRequest.java
  src/main/java/com/seasonthon/YEIN/user/api/dto/response/UpdateProfileResponse.java
  src/main/java/com/seasonthon/YEIN/user/application/UserService.java
Labels: feat

#83 feat/#77: 사용자 정보 조회 API 구현
  src/main/java/com/seasonthon/YEIN/gallery/domain/repository/GalleryRepository.java
  src/main/java/com/seasonthon/YEIN/post/application/PostService.java
  src/main/java/com/seasonthon/YEIN/post/domain/repository/LikeRepository.java
  src/main/java/com/seasonthon/YEIN/user/api/UserController.java
  src/main/java/com/seasonthon/YEIN/user/api/dto/response/UserProfileResponse.java
  src/main/java/com/seasonthon/YEIN/user/application/UserService.java
Labels: feat

#85 fix/#84: 필사 갤러리 필터링 한국 시간대로 변경
  src/main/java/com/seasonthon/YEIN/YeinApplication.java
  src/main/java/com/seasonthon/YEIN/gallery/application/GalleryService.java
  src/main/java/com/seasonthon/YEIN/gallery/domain/repository/GalleryRepository.java
  src/main/java/com/seasonthon/YEIN/global/config/JpaConfig.java
  src/main/resources/application.yml
Labels: fix
